<?php
// i18n-map.php @generated by automattic/jetpack-composer-plugin
return array(
  'domain' => 'zero-bs-crm',
  'type' => 'plugins',
  'packages' => array(
    'jetpack-assets' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-assets',
      'ver' => '1.18.13-alpha1697744587',
    ),
  ),
);
