#!/usr/bin/env bash
#
# Assembles dist/zero-bs-crm/ and dist/zero-bs-crm.zip.
#
# Jetpack CRM is a COMPILED plugin: the Jetpack Composer autoloader
# (vendor/autoload_packages.php, loaded at ZeroBSCRM.php:41), the webpack-built
# `build/lib/*` front-end libraries (loaded at e.g.
# ZeroBSCRM.OnboardMe.php:33), and the compiled *.min.css / *.min.js next to
# their sources are ALL git-ignored (see .gitignore). A plain `git archive` of
# tracked files alone would therefore ship a plugin that fatals on activation.
# So this script builds in layers:
#
#   1. Base: `git archive HEAD` of the ship_paths allow-list below — the tracked
#      runtime source, and ONLY that. A newly-added dev file (docs, tooling,
#      config, a new top-level directory) can never leak into the release unless
#      it is explicitly added here.
#   2. Composer (in the staged dir, WP Job Manager style): copy composer.json +
#      composer.lock into the staged plugin and run `composer install --no-dev`
#      THERE, so the autoloader/vendor are generated in place, runtime-only, and
#      the developer's own working-tree vendor/ is never touched or pruned.
#   3. Assets (in the working tree): run `npm run build-production`, then copy
#      the generated webpack `build/` tree and compiled CSS/JS into the staged
#      plugin. npm/webpack must run at the repo root — it needs node_modules,
#      webpack.config.js and the sass sources, none of which ship — but it is
#      non-destructive, so building in-tree is safe.
#
# STAGING DIR is `dist/`, NOT `build/`. `build/` is reserved: it is webpack's own
# output directory (a runtime asset dir that ships) and `npm run clean` does
# `rm -rf build`, which would wipe our staging mid-build if the two collided.
#
# When you add a new runtime SOURCE file/dir, add it to ship_paths. New built
# assets are picked up automatically.

set -euo pipefail

command -v git >/dev/null || { >&2 echo "git is required"; exit 1; }
command -v zip >/dev/null || { >&2 echo "zip is required"; exit 1; }
command -v composer >/dev/null || { >&2 echo "composer is required"; exit 1; }
command -v npm >/dev/null || { >&2 echo "npm is required"; exit 1; }

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

PLUGIN_SLUG="zero-bs-crm"
BUILD_DIR="dist"
PLUGIN_DIR="$BUILD_DIR/$PLUGIN_SLUG"

# The only tracked paths that ship in the plugin.
ship_paths=(
	ZeroBSCRM.php
	readme.txt
	SECURITY.md
	admin
	api
	css
	data
	html
	i
	includes
	js
	languages
	licenses
	modules
	public
	src
	templates
)

# Whole generated directories to copy from the working tree (webpack output).
# vendor/ and jetpack_vendor/ are NOT here — they are generated by the composer
# step inside the staged dir below.
generated_dirs=(
	build
)

# Directories that may contain scattered built (git-ignored) CSS/JS to overlay.
# Kept as an allow-list so the overlay never rsyncs from node_modules/ or .cache.
asset_dirs=(
	admin
	api
	css
	includes
	js
	modules
	public
	src
	templates
)

rm -rf "$BUILD_DIR"
mkdir -p "$PLUGIN_DIR"

# --- Layer 1: tracked runtime source at HEAD ---------------------------------
git archive HEAD -- "${ship_paths[@]}" | tar -x -C "$PLUGIN_DIR"

# --- Layer 2: composer install --no-dev, IN the staged dir -------------------
# Copy the manifests in, install runtime deps there, then strip the manifests so
# they don't ship. The developer's working-tree vendor/ is never touched.
echo "Installing runtime Composer dependencies (--no-dev) into the staged plugin ..."
cp composer.json composer.lock "$PLUGIN_DIR/"
( cd "$PLUGIN_DIR" && composer install --no-dev --prefer-dist --no-progress --no-interaction --optimize-autoloader )
rm -f "$PLUGIN_DIR/composer.json" "$PLUGIN_DIR/composer.lock"

# --- Layer 3: build assets in the working tree and overlay -------------------
echo "Building production assets ..."
if [ -f package-lock.json ]; then
	npm ci
else
	npm install
fi
# `npm run build-production` runs `npm run clean` (rm -rf build) then webpack;
# it only touches build/ and the compiled css/js, never our dist/ staging.
npm run build-production

echo "Overlaying generated directories ..."
for dir in "${generated_dirs[@]}"; do
	if [ -d "$dir" ]; then
		cp -R "$dir" "$PLUGIN_DIR/"
	else
		>&2 echo "warning: expected generated dir '$dir' not found after build"
	fi
done

# Scattered compiled CSS/JS: copy every git-ignored built asset under the
# asset_dirs, preserving its path. `git ls-files --others --ignored` lists
# exactly the files the build just generated; the dir and extension filters keep
# it to shipped CSS/JS and out of node_modules/vendor/.cache.
echo "Overlaying compiled CSS/JS ..."
while IFS= read -r f; do
	case "$f" in
		*.css|*.min.js|*.min.js.LICENSE.txt) ;;
		*) continue ;;
	esac
	top="${f%%/*}"
	for allowed in "${asset_dirs[@]}"; do
		if [ "$top" = "$allowed" ]; then
			mkdir -p "$PLUGIN_DIR/$(dirname "$f")"
			cp "$f" "$PLUGIN_DIR/$f"
			break
		fi
	done
done < <(git ls-files --others --ignored --exclude-standard)

( cd "$BUILD_DIR" && zip -rq "$PLUGIN_SLUG.zip" "$PLUGIN_SLUG" )

echo "Built $BUILD_DIR/$PLUGIN_SLUG.zip"
